---
# tasks file for java_app_deploy
- name: Get instance details
  ec2_instance_info:
    region: "ap-south-1"
    filters:
      "private-ip-address": "{{ PRIVATE_IP }}"
  register: ec2_instance

- name: Debug
  debug:
    var: ec2_instance
- name: Get instance ID
  set_fact:
    region: "ap-south-1"
    instance_id: "{{ ec2_instance.instances[0].instance_id }}"
      
      
      
- name: Detach from target group
  elb_target:
    region: "ap-south-1"
    target_id: "{{  instance_id }}"
    target_group_name: "{{  target_group  }}"
    state: absent
    

- name: Upload jar
  shell:
    src: "aws s3 cp /home/Ubuntu/sample.simple-1.1.3 s3://mavenartifact/snapshot/"  


- name: Run the jar
  shell: "java -jar s3://mavenartifact/jar/sample.simple-1.1.3 &"


- name: Attach to target group
  elb_target:
    region: "ap-south-1"
    target_id: "{{ instance_id  }}"
    target_group_name: "{{  target_group  }}"
    state: present
