---
- name: found operating system
  ansible.builtin.setup:

- name: Install java on ubuntu 
  apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install java on Red Hat
  yum:
    name: "java-{{ java_version }}-openjdk-devel"
    state: present
  when: ansible_facts['os_family'] == "RedHat"
